am4core.ready(function () {
  am4core.useTheme(am4themes_dataviz);
  am4core.useTheme(am4themes_animated);

  var chart0042 = am4core.create('chartdiv_0042', am4charts.XYChart);
  chart0042.data = data_1;

  var categoryAxis = chart0042.xAxes.push(new am4charts.CategoryAxis());
  categoryAxis.dataFields.category = 'year';
  var valueAxis = chart0042.yAxes.push(new am4charts.ValueAxis());
  valueAxis.renderer.minLabelPosition = 0;
  valueAxis.min = 1;
  var title = chart0042.titles.create();
  title.text = '台灣 COVID-19 疫情資料彙整 (2021/05/14~2021/05/31)';
  title.fontSize = 16;
  title.marginBottom = 0;

  var series1 = chart0042.series.push(new am4charts.LineSeries());
  series1.dataFields.valueY = 'Confirmed';
  series1.dataFields.categoryX = 'year';
  series1.name = '累計確診';
  series1.tooltipText = '{name}: {valueY}';
  series1.strokeWidth = 4;
  series1.stroke = am4core.color('#28a745');
  var bullet1 = series1.bullets.push(new am4charts.CircleBullet());
  bullet1.circle.strokeWidth = 1.6;
  bullet1.circle.radius = 1.6;
  bullet1.circle.fill = am4core.color('#fff');
  var bullethover1 = bullet1.states.create('hover');
  bullethover1.properties.scale = 4;
  var series2 = chart0042.series.push(new am4charts.LineSeries());
  series2.dataFields.valueY = 'Deaths';
  series2.dataFields.categoryX = 'year';
  series2.name = '累計死亡';
  series2.tooltipText = '{name}: {valueY}';
  series2.strokeWidth = 4;
  series2.stroke = am4core.color('#000000');
  var bullet2 = series2.bullets.push(new am4charts.CircleBullet());
  bullet2.circle.strokeWidth = 1.6;
  bullet2.circle.radius = 1.6;
  bullet2.circle.fill = am4core.color('#fff');
  var bullethover2 = bullet2.states.create('hover');
  bullethover2.properties.scale = 4;
  var series3 = chart0042.series.push(new am4charts.LineSeries());
  series3.dataFields.valueY = 'Recovered';
  series3.dataFields.categoryX = 'year';
  series3.name = '解除隔離';
  series3.tooltipText = '{name}: {valueY}';
  series3.strokeWidth = 4;
  series3.stroke = am4core.color('#0099cc');
  var bullet3 = series3.bullets.push(new am4charts.CircleBullet());
  bullet3.circle.strokeWidth = 1.6;
  bullet3.circle.radius = 1.6;
  bullet3.circle.fill = am4core.color('#fff');
  var bullethover3 = bullet3.states.create('hover');
  bullethover3.properties.scale = 4;
  var series4 = chart0042.series.push(new am4charts.LineSeries());
  series4.dataFields.valueY = 'Active';
  series4.dataFields.categoryX = 'year';
  series4.name = '尚在隔離';
  series4.tooltipText = '{name}: {valueY}';
  series4.strokeWidth = 4;
  series4.stroke = am4core.color('#ff0000');
  var bullet4 = series4.bullets.push(new am4charts.CircleBullet());
  bullet4.circle.strokeWidth = 1.6;
  bullet4.circle.radius = 1.6;
  bullet4.circle.fill = am4core.color('#fff');
  var bullethover4 = bullet4.states.create('hover');
  bullethover4.properties.scale = 4;
  chart0042.cursor = new am4charts.XYCursor();
  chart0042.cursor.behavior = 'none';
  chart0042.legend = new am4charts.Legend();
});
